# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.0
_src_path: gh:radio-aktywne/template-database-generic
accountname: radio-aktywne
databasename: emitimes
description: Emission times 🕒
docs: true
docsurl: https://radio-aktywne.github.io/database-emitimes
envprefix: EMITIMES
imagename: databases/emitimes
registry: true
releases: true
reponame: database-emitimes
repourl: https://github.com/radio-aktywne/database-emitimes
