# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.1
_src_path: gh:radio-aktywne/template-database-generic
accountname: radio-aktywne
databasename: datatimes
description: Emission times database 🕒
docs: true
docsurl: https://radio-aktywne.github.io/database-datatimes
envprefix: DATATIMES
imagename: databases/datatimes
registry: true
releases: true
reponame: database-datatimes
repourl: https://github.com/radio-aktywne/database-datatimes
