---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.1
_src_path: gh:radio-aktywne/template-app-generic
accountname: radio-aktywne
appname: emitimes
description: Emission times 🕒
docs: true
docsurl: https://radio-aktywne.github.io/app-emitimes
envprefix: EMITIMES
imagename: apps/emitimes
registry: true
releases: true
reponame: app-emitimes
repourl: https://github.com/radio-aktywne/app-emitimes
