services:
  emitimes:
    build:
      context: ./
      network: host
    environment:
      - "EMITIMES_HOST=${EMITIMES_HOST:-0.0.0.0}"
      - "EMITIMES_PORT=${EMITIMES_PORT:-36000}"
      - "EMITIMES_USER=${EMITIMES_USER:-user}"
      - "EMITIMES_PASSWORD=${EMITIMES_PASSWORD:-password}"
      - "EMITIMES_CALENDAR=${EMITIMES_CALENDAR:-emitimes}"
    network_mode: host
    volumes:
      - data:/database/data/

volumes:
  data: {}
