services:
  datatimes:
    build:
      context: ./
      network: host
    environment:
      - "DATATIMES__SERVER__HOST=${DATATIMES__SERVER__HOST:-0.0.0.0}"
      - "DATATIMES__SERVER__PORT=${DATATIMES__SERVER__PORT:-36000}"
      - "DATATIMES__CREDENTIALS__USER=${DATATIMES__CREDENTIALS__USER:-user}"
      - "DATATIMES__CREDENTIALS__PASSWORD=${DATATIMES__CREDENTIALS__PASSWORD:-password}"
      - "DATATIMES__CALENDAR=${DATATIMES__CALENDAR:-datatimes}"
    network_mode: host
    volumes:
      - data:/database/data/

volumes:
  data: {}
